// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDI.Api.Infrastructure.EfCore;

#nullable disable

namespace NDI.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231207232606_AddDefaultValues")]
    partial class AddDefaultValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NDI.Api.Domain.Entities.Information", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LinkString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MemoryCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("MemoryCardId");

                    b.ToTable("Informations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86902afa-f426-48d5-b4c1-a82c750e1270"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1913), new TimeSpan(0, 1, 0, 0, 0)),
                            LinkString = "https://reseauactionclimat.org/comprendre-urgence/",
                            LongDescription = "Le réchauffement climatique est un phénomène d'augmentation de la température moyenne des océans et de l'atmosphère, à l'échelle mondiale, qui se manifeste par des changements de la variabilité du climat et par des augmentations de la température moyenne des océans et de l'atmosphère, à l'échelle mondiale, qui se manifeste par des changements de la variabilité du climat et par des augmentations de la température moyenne de la surface terrestre.",
                            MemoryCardId = new Guid("57418d78-a860-469d-abd9-01237f6193cd"),
                            ShortDescription = "Le réchauffement climatique est un phénomène d'augmentation de la température moyenne des océans et de l'atmosphère",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1916), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("dd9a74c0-7737-4ed7-9d00-04a9760c8ccc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1938), new TimeSpan(0, 1, 0, 0, 0)),
                            LinkString = "https://reseauactionclimat.org/comprendre-urgence/",
                            LongDescription = "La pollution est un phénomène qui affecte la qualité de l'environnement, qui est lié à l'activité humaine et qui a des conséquences plus ou moins graves sur la santé humaine, les écosystèmes et la biodiversité.",
                            MemoryCardId = new Guid("992393eb-2477-4801-bff8-20de38ec4d90"),
                            ShortDescription = "La pollution est un phénomène qui affecte la qualité de l'environnement",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1941), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("834e4178-554e-4f8d-b209-e65af96a897c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1947), new TimeSpan(0, 1, 0, 0, 0)),
                            LinkString = "https://reseauactionclimat.org/comprendre-urgence/",
                            LongDescription = "Parallèlement à la hausse des températures, le GIEC met en avant deux autres indicateurs qui sont « dans le rouge » et qui attestent des changements climatiques en cours : la fonte des glaces et l'élévation du niveau des mers. La fonte des glaces est un phénomène qui affecte la qualité de l'environnement, qui est lié à l'activité humaine et qui a des conséquences plus ou moins graves sur la santé humaine, les écosystèmes et la biodiversité.",
                            MemoryCardId = new Guid("283ff76d-0e6c-4b11-9fb7-44a566e67e8a"),
                            ShortDescription = "Parallèlement à la hausse des températures, le GIEC met en avant deux autres indicateurs qui sont « dans le rouge » et qui attestent des changements climatiques en cours",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1950), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7c85dd0e-6dbc-4fb4-91b6-2e8e2cdcb590"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1956), new TimeSpan(0, 1, 0, 0, 0)),
                            LinkString = "https://reseauactionclimat.org/6e-rapport-du-giec-quelles-solutions-face-au-changement-climatique/",
                            LongDescription = "Les transports représentent le premier secteur émetteur de gaz à effet de serre en France (31%) et sont responsables d’un quart des émissions mondiales : leur décarbonation est donc un enjeu majeur dans la lutte contre le changement climatique. Parmi les actions identifiées par le GIEC dans tous les secteurs pour réduire les émissions de gaz à effet de serre en transformant les comportements individuels, celles qui concernent la mobilité sont celles qui présentent le plus grand potentiel de réduction de l’empreinte carbone. Les solutions citées par le rapport sont :\n\nDonner la priorité à une mobilité sans voiture, en privilégiant la marche et le vélo par exemple ;\n\nPrivilégier les transports en commun ;\n\nFavoriser les mobilités électriques ;\n\nRéduire les voyages en avion (surtout les vols longs courriers).\n\nÀ l’échelle des villes, une réorganisation des zones urbaines permettrait de réduire la consommation de carburant liée au transport urbain d’environ 25 %, notamment grâce à des infrastructures de transport moins dépendantes de la voiture et à un rapprochement entre le domicile et le lieu de vie.\nConcernant l’aviation, responsable à elle seule de 2,4% des émissions anthropiques de CO2, le GIEC rapporte qu’aucune amélioration en termes d’efficacité énergétique ne permettra de suivre le rythme de la croissance prévue du transport aérien. La limitation du trafic resterait donc le moyen le plus efficace pour réduire les émissions du secteur.\n\nUne action politique forte est indispensable pour effectuer ces transitions : il est nécessaire de proposer des aides et des options aux individus pour les accompagner dans ces changements d’habitudes de mobilité",
                            MemoryCardId = new Guid("582bed60-40ef-4027-980f-7fe9367d6921"),
                            ShortDescription = "Les transports représentent le premier secteur émetteur de gaz à effet de serre en France (31%) et sont responsables d’un quart des émissions mondiales : leur décarbonation est donc un enjeu majeur dans la lutte contre le changement climatique.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1959), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7830f4eb-428b-48fd-95a0-11869e85d8da"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1966), new TimeSpan(0, 1, 0, 0, 0)),
                            LinkString = "https://reseauactionclimat.org/6e-rapport-du-giec-quelles-solutions-face-au-changement-climatique/",
                            LongDescription = "Le secteur de l’agriculture, des forêts et de la gestion des sols présente lui aussi de nombreuses options pour l’atténuation.\n\nLes pratiques agroécologiques (réduction de l’utilisation d’engrais de synthèse, diversification des cultures, meilleure gestion des déjections animales…) permettent de limiter les émissions de gaz à effet de serre, de mieux stocker le CO2 dans les sols et apportent de multiples autres bénéficesprotection de la biodiversité, meilleure qualité de l’eau, de l’air et des sols, sécurité alimentaire… L’agroforesterie, c’est-à-dire l’association d’arbres, de cultures et/ou de bétail sur une même parcelle, montre également un fort potentiel d’atténuation.\n\nLes forêts et écosystèmes absorbent du carbone, il est donc important de les protéger et de lutter contre la déforestation. Toutefois, cela ne pourra pas compenser la réduction des émissions, qui doit rester la priorité dans tous les secteurs.\n\nLe GIEC confirme par ailleurs que le passage à des régimes alimentaires riches en protéines végétales (légumes secs, céréales) et pauvres en viande et en produits laitiers permettent une forte réduction des émissions de GES.",
                            MemoryCardId = new Guid("798fe6ff-a647-4691-94a6-bffe03370545"),
                            ShortDescription = "Le secteur de l’agriculture, des forêts et de la gestion des sols présente lui aussi de nombreuses options pour l’atténuation.\n\nLes pratiques agroécologiques (réduction de l’utilisation d’engrais de synthèse, diversification des cultures, meilleure gestion des déjections animales…) permettent de limiter les émissions de gaz à effet de serre, de mieux stocker le CO2 dans les sols et apportent de multiples autres bénéfices",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1969), new TimeSpan(0, 1, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("NDI.Api.Domain.Entities.MemoryCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("MemoryCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57418d78-a860-469d-abd9-01237f6193cd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1794), new TimeSpan(0, 1, 0, 0, 0)),
                            Title = "Le réchauffement climatique",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1850), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("992393eb-2477-4801-bff8-20de38ec4d90"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1860), new TimeSpan(0, 1, 0, 0, 0)),
                            Title = "La pollution",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1863), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("283ff76d-0e6c-4b11-9fb7-44a566e67e8a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1866), new TimeSpan(0, 1, 0, 0, 0)),
                            Title = "La fonte des glaces",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1869), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("582bed60-40ef-4027-980f-7fe9367d6921"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1892), new TimeSpan(0, 1, 0, 0, 0)),
                            Title = "Transports : transformer les mobilités individuelles",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1895), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("798fe6ff-a647-4691-94a6-bffe03370545"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1899), new TimeSpan(0, 1, 0, 0, 0)),
                            Title = "Agriculture et alimentation : moins de viande, plus de pratiques durables",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 12, 8, 0, 26, 5, 872, DateTimeKind.Unspecified).AddTicks(1901), new TimeSpan(0, 1, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("NDI.Api.Domain.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("NbError")
                        .HasColumnType("int");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Time")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("NDI.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NDI.Api.Domain.Entities.Information", b =>
                {
                    b.HasOne("NDI.Api.Domain.Entities.MemoryCard", null)
                        .WithMany("Informations")
                        .HasForeignKey("MemoryCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NDI.Api.Domain.Entities.Score", b =>
                {
                    b.HasOne("NDI.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NDI.Api.Domain.Entities.MemoryCard", b =>
                {
                    b.Navigation("Informations");
                });
#pragma warning restore 612, 618
        }
    }
}
